# Generated by Django 3.2.8 on 2021-11-03 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledgers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=40)),
                ('total', models.FloatField()),
                ('description', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=20)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledgers.ledger')),
            ],
        ),
    ]
