# Generated by Django 3.2.8 on 2021-11-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_id', models.IntegerField()),
                ('ledger_name', models.CharField(max_length=30)),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LedgerTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
            ],
        ),
    ]
